### ISSUE TITLE
Authentication method doesn't work

### ISSUE THREAD

**Issue by wefner** [ork/mutt-office365#1]
Receiving e-mail works although when trying to send it complains "Authentication method missing". I've tried several changes with no luck. Did you experience something similar? I've read documentation from mutt and non of their auth methods work.

Using mutt-1.5.20-4.20091214hg736b6a.el6_5.x86_64 in a CentOS 6.5

**Comment by Samaliel** [comment]
I have mutt installed on mac via brew .
I receive the mail perfectly
but when sending
An authenticity verification method is missing.
Can anybody help me please

**Comment by knutid** [comment]
@Samaliel, ref. [wefner on 2014-08-21](https://github.com/ork/mutt-office365/issues/1#issuecomment-52898280), try installing [cyrus-sasl](https://formulae.brew.sh/formula/cyrus-sasl) via Homebrew? (Disclaimer: not tested as I do not have partial-eaten-apple stuff.)
