### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by k0pernikus** [ork/mutt-office365#10]
Since a few days, I cannot log into my account anymore. Mutt only states `Login failed`. I still can 
use the web frontend fine. Is there any more information I could provide?

![login-failed](https://cloud.githubusercontent.com/assets/436935/13875651/76411122-ecff-11e5-8cd5-1faf68c06de8.gif)

**Comment by k0pernikus** [comment]
@ork Is there any more information I could provide? I really would like to get mutt working again.

**Comment by k0pernikus** [comment]
While setting up a different email client, my login credential wouldn't work. When I logged out of the office365 webapp and tried to login there to check my credentials, I was suddenly required update my password as it was claimed to either never been used or expired.

After setting a new password, mutt works again. So it was an issue with outlook itself o.0

@ork Maybe you can parse the error or give a hint if such an error occurs to update one's password.

**Comment by ork** [comment]
I noticed the same behaviour when my precedent password expired. This clearly needs a wiki entry.

**Comment by jon-peel** [comment]
I am not able to log into Mutt (Ubuntu).
I did try logging in and out of the Outlook web portal, and that works with no trouble.
When I try in Mutt I get: "Login Failed."

Any quick checks you can think for me to look at?

**Comment by jon-peel** [comment]
A follow-up.
I installed neomutt, and that does work.
Guessing it is a version or library issue.

**Comment by jon-peel** [comment]
Another follow-up.
I can receive emails using neomutt, but when I try and send an email I get the error "SASL authentication failed"

**Comment by jon-peel** [comment]
Follow-up again.
Doing this with debugging enabled, I see a message saying SMTP is not enabled on this TENENT. so I have MS config to do...

**Comment by ghost** [comment]
> Another follow-up. I can receive emails using neomutt, but when I try and send an email I get the error "SASL authentication failed"

I know this is an old issue but I have the opposite problem, in my numerous attemps to set up mutt to use my university outlook, I've only managed to successfully send emails but not to receive or read anything.
I tried both using these configuration files and writing my own.

Moreover, by googling around forums, repos and websites I noticed that no one uses [this smtp address](https://support.microsoft.com/en-au/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040). Unfortunately, in my case, even by using them, mutt gives me login failed
![Screenshot from 2023-12-30 13-11-42](https://github.com/ork/mutt-office365/assets/62035219/217215ee-ce02-46d3-87a1-1eec3ac4ee0e)
