### ISSUE TITLE
Error with language de_DE

### ISSUE THREAD

**Issue by mystygage** [ork/mutt-office365#11]
I get this error during startup:

```
Error in /Users/user/.mutt/muttrc, line 22: trash: unknown variable
source: errors in /Users/user/.mutt/muttrc
Press any key to continue...
```

I use mutt 1.6.1 and set `my_lang` to `de_DE`.

**Comment by ork** [comment]
Hallo,
It seems like you're not using the _trash_ patchset for mutt that add this feature. Many distributions provide a heavily patched mutt version. You could either upgrade to one of these versions, apply the patch yourself, or not use this feature.
