### ISSUE TITLE
No folders

### ISSUE THREAD

**Issue by xerosis** [ork/mutt-office365#5]
I've setup my office 365 mailbox as explained in the README, it works fine but it's coming up with no folders other than the inbox.

**Comment by ork** [comment]
Can you check in Thunderbird if these folders that are missing as well? If they are missing too, maybe you didn't [subscribe](http://kb.mozillazine.org/IMAP:_advanced_account_configuration#May_help_prevent_problems) to them.

If these folders are not subscribed by default, I will add a simple setup script to do it.

**Comment by xerosis** [comment]
Yeah they just weren't subscribed, thanks.

**Comment by frakman1** [comment]
How do I subscribe? I have the same problem. Only the Inbox shows up. `c?` shows nothing, although the keybinding to go to the Sent folder works.
