### ISSUE TITLE
How to revert listing of the mails?

### ISSUE THREAD

**Issue by k0pernikus** [ork/mutt-office365#9]
I want to list the emails in reverse, so that the most current revieved email stands at the top and not as it is now, on the bottom.

I tried the setting:

```
set sort_aux=last-date-received       
set sort=threads
set sort_re
```

Yet it seems to be ignored. Can I revert some other way?

**Comment by ork** [comment]
This showed a reverse threaded message browser sorted by date.
```
set sort_browser = reverse-date
set sort_aux = reverse-date-received
```

Can you reproduce the result?

**Comment by k0pernikus** [comment]
@ork :+1: Yes, I can confirm that this reverts the mail listing.
